services:
  kpow:
    image: factorhouse/kpow-ce:latest
    container_name: kpow-ce
    pull_policy: always
    restart: always
    ports:
      - "4000:3000"
    environment:
      ENVIRONMENT_NAME: "Instaclustr Kafka Cluster"
      BOOTSTRAP: ${KAFKA_BOOTSTRAP_SERVERS}
      SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      SASL_MECHANISM: "SCRAM-SHA-256"
      # prettier-ignore
      SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USER}\" password=\"${KAFKA_PASSWORD}\";"
    env_file:
      - ${FACTOR_HOUSE_CE_LICENSE:-license.env}

  flex:
    image: factorhouse/flex-ce:latest
    container_name: flex-ce
    pull_policy: always
    restart: always
    ports:
      - "5000:3000"
    depends_on:
      jobmanager:
        condition: service_healthy
    environment:
      FLINK_ENVIRONMENT_NAME: "Standalone Flink Cluster"
      FLINK_REST_URL: http://jobmanager:8081
      ALLOW_FLINK_SUBMIT: "true"
      ALLOW_FLINK_JOB_TERMINATE: "true"
      ALLOW_FLINK_JAR_DELETE: "true"
      ALLOW_FLINK_JOB_EDIT: "true"
    env_file:
      - ${FACTOR_HOUSE_CE_LICENSE:-license.env}

  jobmanager:
    image: flink:1.20.1
    container_name: jobmanager
    command: jobmanager
    ports:
      - "18081:8081"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - INITIAL_PRODUCTS_FILE=${INITIAL_PRODUCTS_FILE}
      - PARALLELISM=${PARALLELISM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/config"]
      interval: 5s
      timeout: 5s
      retries: 5

  taskmanager:
    image: flink:1.20.1
    container_name: taskmanager
    command: taskmanager
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - INITIAL_PRODUCTS_FILE=${INITIAL_PRODUCTS_FILE}
      - PARALLELISM=${PARALLELISM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    depends_on:
      jobmanager:
        condition: service_healthy
