package com.ververica.composable_job.model.ecommerce;

public enum EcommerceEventType {
    PAGE_VIEW,
    PRODUCT_VIEW,
    PRODUCT_SEARCH,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    UPDATE_CART_QUANTITY,
    CART_VIEW,
    CHECKOUT_START,
    CHECKOUT_COMPLETE,
    PAYMENT_PROCESSED,
    ORDER_PLACED,
    RECOMMENDATION_VIEWED,
    RECOMMENDATION_CLICKED,
    USER_LOGIN,
    USER_LOGOUT,
    WISHLIST_ADD,
    WISHLIST_REMOVE,
    REVIEW_SUBMITTED,
    CATEGORY_BROWSE
}